## Exercises for Chapter 1

In [1]:
import numpy as np

### 1.1

d) is true

### 1.2

c) The result is a matrix

### 1.3

a) The result is true if B is a column vector

### 1.4

d) The rank of an $n \times  n$ identity matrix is $n$

### 1.5

c) The rank of an $n \times m$ matrix is not greater than $\text{min}(m, n)$

### 1.6

b) The last column of a transposed matrix is the same as the last row of the original matrix but transposed

### 1.7

c) A complete market means that the rank of the payoff matrix is m

### 1.8

a) When there are more securities than states in the world this means that some securities are redundant

### 1.9

c) The number of redundant securities is eual to $n-r(A)$

### 1.10

c) A payoff matrix with full rank means that the market is complete, there are no redundant securities, or sometimes both

### 1.11

In [22]:
A = np.zeros((8, 2))

A[:, 0] = 2
A[:, 1] = np.array([-20, -10, -5, 0, 5, 10, 20, 30])

# convert to decimal and calculate returns
A /= 100
A *= 10_000

print('a)\n')

print('Payoff matrix:')
print(A)

print('Terminal wealth matrix:')
print(10_000 + A)

a)

Payoff matrix:
[[  200. -2000.]
 [  200. -1000.]
 [  200.  -500.]
 [  200.     0.]
 [  200.   500.]
 [  200.  1000.]
 [  200.  2000.]
 [  200.  3000.]]
Terminal wealth matrix:
[[10200.  8000.]
 [10200.  9000.]
 [10200.  9500.]
 [10200. 10000.]
 [10200. 10500.]
 [10200. 11000.]
 [10200. 12000.]
 [10200. 13000.]]


In [23]:
probabilities = np.array([0.05, 0.1, 0.15, 0.2, 0.2, 0.15, 0.1, 0.05])

A[:, 1] = A[:, 1] * probabilities

print('b\n')

print('Expected terminal wealth matrix:')
print(A)

b

Expected terminal wealth matrix:
[[ 200. -100.]
 [ 200. -100.]
 [ 200.  -75.]
 [ 200.    0.]
 [ 200.  100.]
 [ 200.  150.]
 [ 200.  200.]
 [ 200.  150.]]
